{% set version = "1.5.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-divemove
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/diveMove_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/diveMove/diveMove_{{ version }}.tar.gz
  sha256: 785779447a5c7d25122328d6b130a46076dcedebf32fd4de577b8a7e890e7bf6

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-kernsmooth
    - r-geosphere
    - r-plotly
    - r-quantreg
    - r-unireg
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-kernsmooth
    - r-geosphere
    - r-plotly
    - r-quantreg
    - r-unireg

test:
  commands:
    - $R -e "library('diveMove')"           # [not win]
    - "\"%R%\" -e \"library('diveMove')\""  # [win]

about:
  home: https://github.com/spluque/diveMove
  license: GPL-3.0-only
  summary: Utilities to represent, visualize, filter, analyse, and summarize time-depth recorder (TDR) data.  Miscellaneous functions for handling location data are also provided.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - alexetnunes

# Package: diveMove
# Type: Package
# Title: Dive Analysis and Calibration
# Version: 1.4.5
# Depends: R (>= 2.13.0), methods, stats4
# Suggests: knitr, lattice, tcltk
# Imports: KernSmooth, quantreg, uniReg, geosphere
# Author: Sebastian P. Luque <spluque@gmail.com>
# Maintainer: Sebastian P. Luque <spluque@gmail.com>
# Description: Utilities to represent, visualize, filter, analyse, and summarize time-depth recorder (TDR) data.  Miscellaneous functions for handling location data are also provided.
# LazyLoad: yes
# LazyData: no
# ZipData: no
# BuildResaveData: no
# VignetteBuilder: knitr
# Collate: AllClass.R AllGenerics.R AllMethod.R austFilter.R bouts.R calibrate.R detDive.R detPhase.R distSpeed.R diveStats.R oneDiveStats.R plotTDR.R plotZOC.R readLocs.R readTDR.R runquantile.R speedStats.R stampDive.R zoc.R zzz.R
# NeedsCompilation: yes
# License: GPL-3
# URL: https://github.com/spluque/diveMove
# Packaged: 2019-01-03 04:40:49 UTC; sluque
# Repository: CRAN
# Date/Publication: 2019-01-03 15:10:03 UTC
