{% set version = "1.4.5" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-divemove
  version: {{ version|replace("-", "_") }}

source:
  fn: diveMove_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/diveMove_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/diveMove/diveMove_{{ version }}.tar.gz
  sha256: caefc11f3f66fe0b8104e5a6db46b02bee8daac8c9a796e03bb9e0e34b2e3352

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-kernsmooth
    - r-catools
    - r-geosphere
    - r-quantreg
    - r-unireg
  run:
    - r-base
    - r-kernsmooth
    - r-catools
    - r-geosphere
    - r-quantreg
    - r-unireg

test:
  commands:
    - $R -e "library('diveMove')"           # [not win]
    - "\"%R%\" -e \"library('diveMove')\""  # [win]

about:
  home: https://github.com/spluque/diveMove
  license: GPL-3
  summary: Utilities to represent, visualize, filter, analyse, and summarize time-depth recorder
    (TDR) data.  Miscellaneous functions for handling location data are also provided.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - alexetnunes
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
