appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ApsjoeyqGHZ8Z0rM0zjlpnUkfmY9JRaQecxfw00Pl1OdO3iCbsb88LQNymV56XHh2kGDILxDGT/NljZNDyPJ++3zJbgNEoOaypltS8862EiN1Eq9d/AFtwUwM0Rzxw71gYBmM3D2w+O+rwusTmTKO0TTB5JREUXyYvS1ZOcqeERs8duES8PW52cQV8enIJEhHKH4v4GRjabWHDpk7DxdUvjRgw3oPfcTL4XiqFA2aHr73Qn/9u9xfWIKnixRHtp/JAiR82W9nT3v6qw+fNOzJKn5KamP3mk9AXJBnTmS0EfK5xQooahrJXXTKiyi5BcHxnjCyo9pq0f8WjyYbwZgDPnOtUwDMFdS4MjBROiiImXTUM0H1RSCleVSJOyI0IvSDMCxcq9NZv4j4TjiKYx4xgQMiWPLFmFHEkEejkLWo0aJlMaWfwvh+OnG1iDSS5bzGFpHw2Hb3afcLLkGEX2DP/kLe4nLtMrDg2Bi476tB7tHxh/Vu4AKCaGAm+18I3+1IgEEQYUEhXp/vq9JakZM07D6oLyxGMi7WaC9RoH2ici0qaOq8faFETxt1U8+/mQm+nFx4UtZ/tBjnAlH+HT4TJzCxjJjVP95DeCTG0LNFjD36Q6MgFAZi0LZVl3VrNh61ft2sCRfIjWhoipefua3UdNk09C8g01s+QdqavjvuZo=}
